### PR TITLE
ctrtransfer: find: NULL is required (2)

### PR DESCRIPTION
**Pull request by Naim2000**
Should we just go straight to digging in essential.exefs instead

### CODE REVIEW

**Comment by fyredragon69** [comment]
has this been tested on a console yet to ensure it won't cause issues? i don't doubt your skills but i want to make sure before merging it

**Comment by ManiacOfGitHub** [comment]
> has this been tested on a console yet to ensure it won't cause issues? i don't doubt your skills but i want to make sure before merging it

I just tested it. This fixes the syntax error. There's no real way this could cause issues

**Comment by ManiacOfGitHub** [comment]
Although, last modified should be updated.

**Comment by fyredragon69** [comment]
last modified date was fixed by me

**Pull request merged**
